Repository matomo-org/plugin-CustomAlerts, pull requests merged in 2023-08, with the labels that each got.

#143 Adjustments for core notification and icon changes
  tests/UI/expected-ui-screenshots/CustomAlerts_edit.png
  tests/UI/expected-ui-screenshots/CustomAlerts_list.png
  tests/UI/expected-ui-screenshots/CustomAlerts_list_triggered.png
Labels: c: Design / UI, Needs Review

#145 Fixed alert condition not reloading on site change
  CHANGELOG.md
  plugin.json
  tests/Fixtures/CustomAlerts.php
  tests/UI/CustomAlerts_spec.js
  tests/UI/expected-ui-screenshots/CustomAlerts_alert_condition_reloaded_site1.png
  tests/UI/expected-ui-screenshots/CustomAlerts_alert_condition_reloaded_site2.png
  tests/UI/expected-ui-screenshots/CustomAlerts_edit.png
  vue/dist/CustomAlerts.umd.js
  vue/dist/CustomAlerts.umd.min.js
  vue/src/EditAlert/EditAlert.vue
Labels: Needs Review

#146 Cherry picked Fixed alert condition not reloading on site change
  CHANGELOG.md
  plugin.json
  tests/Fixtures/CustomAlerts.php
  tests/UI/CustomAlerts_spec.js
  tests/UI/expected-ui-screenshots/CustomAlerts_alert_condition_reloaded_site1.png
  tests/UI/expected-ui-screenshots/CustomAlerts_alert_condition_reloaded_site2.png
  tests/UI/expected-ui-screenshots/CustomAlerts_edit.png
  vue/dist/CustomAlerts.umd.js
  vue/dist/CustomAlerts.umd.min.js
  vue/src/EditAlert/EditAlert.vue
Labels: Needs Review

#148 Update UI screenshot tests for core dropdown adjustments
  tests/UI/expected-ui-screenshots/CustomAlerts_alert_condition_reloaded_site1.png
  tests/UI/expected-ui-screenshots/CustomAlerts_alert_condition_reloaded_site2.png
  tests/UI/expected-ui-screenshots/CustomAlerts_edit.png
Labels: c: Design / UI
